### ISSUE TITLE
No hardware wallet support [ --device ] 

### ISSUE THREAD

**Issue by plowsof** [flathub/org.getmonero.Monero#1]
Hello, at least 2 users on Reddit have confirmed their hardware wallets not being detected and the `--device` setting was suggested as the reason:

https://github.com/flathub/org.getmonero.Monero/blob/d9f08c50620844b46291220b03b295a9126131fc/org.getmonero.Monero.yaml#L6

`--device=all ` would be the required setting right? this would also allow for a webcam qr code scanner to be supported by this flatpak in the future (if one is added to the client)

**Comment by sanecito** [comment]
Said source of users raising the Ledger issue:

https://www.reddit.com/r/Monero/comments/oeco87/as_of_today_monero_gui_is_available_as_a_flatpak/h4612mw?utm_source=share&utm_medium=web2x&context=3

**Comment by BigmenPixel0** [comment]
Thanks for the report! Now I'll add --device = all and tell me if the hardware wallet will now work

**Comment by zocker-160** [comment]
[according to a user on reddit](https://www.reddit.com/r/Monero/comments/oeco87/as_of_today_monero_gui_is_available_as_a_flatpak/h4aaqlb?utm_source=share&utm_medium=web2x&context=3) this does fix the issue with USB ledgers

**Comment by plowsof** [comment]
Thanks for the update Z! And thank you for adding the fix BP! (this is how the fix appeared to me in Ubuntu 20.04 fwiw)
- 'show applications' (those 9 dots)
- right click on the Monero icon -> Show details
- An 'update' button now showing -> after clicking, permissions == "high" 

I can also confirm it works now, so this issue is closed, once again, thanks everyone!
