### ISSUE TITLE
Filesystem access on Mint 23.1

### ISSUE THREAD

**Issue by mateMathieu** [flathub/org.getmonero.Monero#101]
Hi,
I can't have access file-paths on Linux Mint.
If I want to select the folder path using the browse button, it does not appear in the wallet configuration during the creation. Return a error with a red path box.

I also cannot select the file-path for the blockchain, that I would like to store on an internal disk (btrfs might be an issue).
Also possible, it is some compatibility issues, or some missing dependencies with Cinnamon and linux mint.

Can you help with this issue?

![Screenshot from 2024-02-01 16-21-44](https://github.com/flathub/org.getmonero.Monero/assets/3027020/98637e90-dabb-487b-97e2-bc8ad307f8c1)

**Comment by BigmenPixel0** [comment]
```
flatpak --user override org.getmonero.Monero --filesystem=/path/to/your/folder
```

**Comment by BigmenPixel0** [comment]
Well, was the problem solved?

**Comment by mateMathieu** [comment]
Hi,
Thanks for your answers, I allowed this flatpak to access the file-path I want to use for the blockchain before posting this issue.

But despite this, there is a general problem with the integration of the flatpak to both the file system and the daemon.
That is why I suggested to look into the flatpak integration to Cinnamon and Linux mint.

Then I tried with ubuntu, and I have the same problem of setting the filepath when "restoring a wallet from hardware".
And when I circumvent it by putting the "/file/path/to/the/right/folder" (which works if manually entered/pasted into the GUI box), the node daemon does not start; both for mint and ubuntu on two different computers.
It reaches 120s threshold and return an error.

So the only real possibilities are that I do something wrong in both cases, or the flatpak framework has evolved and needs to be updated. 
I will update in 10 days as I am away for now.

**Comment by BigmenPixel0** [comment]
One can just allow `--filesystem=host` and have the access to all the files but it's unsafe. Also, some applications can use portals so that one can have the access to many files without `--filesystem=host ` or similar.

**Comment by BigmenPixel0** [comment]
> ![Screenshot from 2024-03-17 00-10-41](https://private-user-images.githubusercontent.com/3027020/313464649-1ade6437-5b90-4352-8e41-d18e1ad5663d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjM1NzUsIm5iZiI6MTcxMDkyMzI3NSwicGF0aCI6Ii8zMDI3MDIwLzMxMzQ2NDY0OS0xYWRlNjQzNy01YjkwLTQzNTItOGU0MS1kMThlMWFkNTY2M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDgyNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI0NWVlNzJlOGI1YzAwZGEyNGFmODQzNmIzZWRhMmM4MjM5ODQ1YjNlZjkyY2YyZGM2ZTAxNzVmY2I4NDRhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nOHDc98yNYREe7cxU8znJ83zTK3um1SYXUzWyGZcTY8) Here is what I get on mint, the file manager being particulate, the flatpack does not seems to be compatible with monerogui.

I don't understand
