### ISSUE TITLE
Can't install P2Pool

### ISSUE THREAD

**Issue by abdulocracy** [flathub/org.getmonero.Monero#18]
When trying to mine with the new P2Pool feature, the app can't install P2Pool in /app/bin.

**Comment by BigmenPixel0** [comment]
Hello. Now added support for p2pool (not tested) to the beta branch. Can you please tell me the result? (you need to wait until the update is assembled and comes)

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.getmonero.Monero
```

**Comment by abdulocracy** [comment]
Unfortunately it still doesn't work, but with a different problem. It just freezes with "Starting P2Pool"

**Comment by BigmenPixel0** [comment]
> Unfortunately it still doesn't work, but with a different problem. It just freezes with "Starting P2Pool"

Can you send me log with this error?

**Comment by BigmenPixel0** [comment]
Are there still problems?

**Comment by plowsof** [comment]
@BigmenPixel0 if you ever want to troubleshoot this (without wasting time synching a full local node) you can point p2pool at a remote one as shown here https://github.com/plowsof/listen_for_zmq ( daily updated list of public nodes https://github.com/plowsof/listen_for_zmq/blob/main/zmq_list.md)
