### ISSUE TITLE
Version v0.18.0.0 Tagged

### ISSUE THREAD

**Issue by dginovker** [flathub/org.getmonero.Monero#22]
https://github.com/monero-project/monero-gui/releases/tag/v0.18.0.0

**Comment by dginovker** [comment]
Just noticed @flathubbot made the last version bump? How does that get triggered? https://github.com/flathub/org.getmonero.Monero/commit/2de8da42f0b98ca4401599ef76c82fc5931240b7

**Comment by BigmenPixel0** [comment]
Stable branch updated to 0.18.0.0.
