### ISSUE TITLE
Impossible to set up new hardware wallet

### ISSUE THREAD

**Issue by ntninja** [flathub/org.getmonero.Monero#27]
Steps to reproduce:

  1. Launch the Monero GUI Flatpak/Flathub application (does not happen with the official website binaries) for the first time or close whatever existing wallet is open
  2. Select language and wallet mode if prompted
  3. Choose *Create a new wallet from hardware*
  4. Observe that nothing happens when clicking on or trying to keyboard-focus the *Choose your hardware wallet* selection box below the *Hardware wallet model* text – hence it is impossible to create a new hardware-backed Monero wallet using the Flatpak

It *is* however possible to open an existing hardware-backed Monero wallet by choosing *Open a wallet from file* in step 3 and this works without issues – or at least without issues not also present in the website version of the Monero GUI application.

**Comment by BigmenPixel0** [comment]
Hello. What's your distribution and DE?

**Comment by ntninja** [comment]
It’s Debian unstable with KDE Plasma 5.24.4 using the default KWin WM.

Thanks!


Am Donnerstag, 18. August 2022 schrieb BigmenPixel:

**Comment by ntninja** [comment]
Yes, that appears to be the same issue. I hadn’t considered that the website version statically links its own Qt, so that must be the difference.

**Comment by BigmenPixel0** [comment]
> Same here.
> 
> Kubuntu 22.04 LTS x86_64 DE: Plasma 5.24.6 WM: KWin Theme: Breeze Install Method: Flatpak Monero Version: 0.18.1.2
> 
> I cannot choose the hardware wallet. The dropdown menu doesn't appear. But when I install the monero wallet from the official website, it works.

Sorry, but I don't know, what to do at this moment. I am just a flatpak maintainer, this is a QT issue, maybe. :)
You can create a new wallet with the monero wallet from the official website and after use the monero wallet from flathub.

**Comment by selsta** [comment]
@BigmenPixel0 can you apply this workaround for flatpak? https://github.com/monero-project/monero-gui/issues/3938#issuecomment-1327914535

**Comment by BigmenPixel0** [comment]
> @BigmenPixel0 can you apply this workaround for flatpak? [monero-project/monero-gui#3938 (comment)](https://github.com/monero-project/monero-gui/issues/3938#issuecomment-1327914535)

I think this problem isn't specific to flatpak and should be fixed upstream

**Comment by BigmenPixel0** [comment]
This issue should be solved, can you check this?
