### ISSUE TITLE
Autostart monerod

### ISSUE THREAD

**Issue by nice42q** [flathub/org.getmonero.Monero#60]
Is there a way to start the application in the background?

Like, ~/.config/autostart/monerod-start.desktop
```
[Desktop Entry]
Type=Application
Name=Monero Daemon
Exec=flatpak run org.getmonero.Monero --detach
Comment=Launch monerod in background
```

**Comment by BigmenPixel0** [comment]
Hello. You can run any command in a container so:
```
flatpak run --command="monerod" org.getmonero.Monero
```

**Comment by BigmenPixel0** [comment]
Hm, yes, I have the same problem. And it's strange that `flatpak run --command="monerod" org.getmonero.Monero` in a terminal works well...

**Comment by BigmenPixel0** [comment]
@nice42q, try so:
```
Exec=flatpak run --command=monerod org.getmonero.Monero --detach
```
